### ISSUE TITLE
the filtering functionality is not displayed

### ISSUE THREAD

**Issue by schildg** [easyredmine/redmine_entity_generator#10]
Hello, I am using this plugin, it generated several simple entities and some others were integrated and also shared the same problems, it did not allow me to make the modification of the recently saved record, besides corroborate with several users / roles with their respective La habilitación para the generated entities, the behavior of the plugin is very different from what is sponsored in the youtube videos with respect to the generated entity.
Next, I pass the problems that I have:
(very important) does not show the box of filters, nor does it allow the selection of each one of the entities for its edition as it is shown in the youtube videos.

![image](https://user-images.githubusercontent.com/29732357/60269840-978b9f80-98c5-11e9-8523-1d004d0fd694.png)

I tested its operation with the gem redmine_extensions 0.3.0 and 0.2.16 and in both I had the same problem, also commented that I am using the theme purple-mine and default of Redmine.

thank you!

**Comment by schildg** [comment]
Here I upload the plugin generated with "redmine_entity_generator", can you review? because the filtering header is not shown, as it is in these screenshots:

https://www.easyredmine.com/images/articles/p8/f2498/gallery96/Easy_Redmine_2018_Redmine_plugin_generator_2.jpg

and options related to filter

https://www.easyredmine.com/images/articles/p8/f2498/gallery96/Easy_Redmine_2018_Redmine_plugin_generator_4.jpg

[redmine_sidesys.zip](https://github.com/easyredmine/redmine_entity_generator/files/3343294/redmine_sidesys.zip)

**Comment by schildg** [comment]
You have corroborated that the zip:
https://github.com/easyredmine/redmine_entity_generator/files/3343294/redmine_sidesys.zip
generated with this plugins, is displayed correctly?
if so, could you tell me in which version of redmine, and what gem of redmine_extensions are you using. or what would I be missing?

the characteristics of the environment in which I am executing are the masses that the #11

**Comment by jiribruk** [comment]
Yes i saw your generated plugin. It is all right. We removed filters and options because the possible combinations were too complicated. As I wrote the generator is intended for the programmers and this part needs to be programmed. 

In video probably was used  redmine_extensions '0.1.16'. 
I don't know exactly. the video did someone else and is 3 years old.

**Comment by schildg** [comment]
238/5000
I am very sorry that the filtering and editing options are not available. Although I am a developer, I would need some code to start creating these filtering options in the generated plugins.

Thank you

**Comment by jiribruk** [comment]
You can find everything you need here: app/views/issues/index.html.erb

**Comment by jiribruk** [comment]
Detailed: 
1) You need to change generated static table to dynamic. I recommend to use partial _list from timelog. 

Now your index.html.erb looks like this
```ruby
# plugins/redmine_sidesys/app/views/pais/index.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:add_pais, @project, global: true) %>
    <%= link_to l(:button_pai_new), new_pai_path, class: 'icon icon-add' %>
  <% end %>
</div>
<h2><%= @query.new_record? ? l(:label_issue_plural) : @query.name %></h2>
<% html_title(@query.new_record? ? l(:label_issue_plural) : @query.name) %>

# added filters
<%= form_tag(pais_path, :method => :get, :id => 'query_form') do %>
  <%= render :partial => 'queries/query_form' %>
<% end %>

<% if @query.valid? %>
  <% if @entities.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render_query_totals(@query) %>
# partial with dynamic table
    <%= render :partial => 'timelog/list', :locals => { :entries => @entities }%>
    <span class="pagination"><%= pagination_links_full @entity_pages, @entity_count %></span>
  <% end %>
<% end %>
```

2) Because list need pagination, you must added code to controller action index.
```ruby
# plugins/redmine_sidesys/app/controllers/pais_controller.rb
  def index
    retrieve_query(PaiQuery, false)
    @entity_count = @query.pais.count
    @entity_pages = Paginator.new @entity_count, per_page_option, params['page']
    @entities = @query.pais(:offset => @entity_pages.offset, :limit => @entity_pages.per_page)
  end
```

3) Last you need added this:
```ruby
# plugins/redmine_sidesys/app/models/pai.rb
def editable_by?(user)
    visible?(user)
end
```
to model.

**Comment by jiribruk** [comment]
Filtrs and options for index returned in version '0.3.3' redmine_extensions

**Comment by schildg** [comment]
Excellent, for when version 0.3.3 will be published

**Comment by jiribruk** [comment]
It was released today

**Comment by schildg** [comment]
Hello, I have the following problem after updating the gem redmine_extensions 0.3.3, when I am generating the entities I throw the following error, why is that?

I, [2019-08-16T10:35:29.193841 #1470]  INFO -- : Started GET "/entity_generator/new" for 192.168.133.1 at 2019-08-16 10:35:29 -0300
I, [2019-08-16T10:35:29.536318 #1470]  INFO -- : Processing by EntityGeneratorController#new as HTML
I, [2019-08-16T10:35:29.546289 #1470]  INFO -- :   Current user: user (id=1)
I, [2019-08-16T10:35:29.654423 #1470]  INFO -- :   Rendered plugins/redmine_entity_generator/app/views/entity_generator/_new_entity.html.erb (9.3ms)
I, [2019-08-16T10:35:29.654599 #1470]  INFO -- :   Rendered plugins/redmine_entity_generator/app/views/entity_generator/_form.html.erb (24.1ms)
I, [2019-08-16T10:35:29.655888 #1470]  INFO -- :   Rendered plugins/redmine_entity_generator/app/views/entity_generator/new.html.erb within layouts/base (54.7ms)
I, [2019-08-16T10:35:29.669594 #1470]  INFO -- :   Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (4.8ms)
I, [2019-08-16T10:35:29.670973 #1470]  INFO -- :   Rendered plugins/advanced_roadmap/app/views/hooks/_stylesheet.html.erb (0.5ms)
I, [2019-08-16T10:35:29.672098 #1470]  INFO -- :   Rendered plugins/extra_queries/app/views/extra_queries/hooks/_html_head.html.erb (0.3ms)
I, [2019-08-16T10:35:29.674004 #1470]  INFO -- :   Rendered plugins/global_roles/app/views/hooks/global_roles/_head.html.erb (0.3ms)
I, [2019-08-16T10:35:29.676107 #1470]  INFO -- :   Rendered plugins/redmine_contacts/app/views/contacts_issues/_additional_assets.html.erb (1.0ms)
I, [2019-08-16T10:35:29.677004 #1470]  INFO -- : redmine_highlightjs2: supported browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
I, [2019-08-16T10:35:29.686025 #1470]  INFO -- :   Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.1ms)
I, [2019-08-16T10:35:29.712519 #1470]  INFO -- :   Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.2ms)
I, [2019-08-16T10:35:29.713708 #1470]  INFO -- :   Rendered plugins/global_roles/app/views/hooks/global_roles/_view_layouts_base_body_bottom.html.erb (0.3ms)
I, [2019-08-16T10:35:29.714801 #1470]  INFO -- :   Rendered plugins/redmine_contacts/app/views/common/_contacts_select2_data.html.erb (0.4ms)
I, [2019-08-16T10:35:29.723339 #1470]  INFO -- :   Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (7.5ms)
I, [2019-08-16T10:35:29.724719 #1470]  INFO -- :   Rendered plugins/redmine_people/app/views/common/_people_select2_data.html.erb (0.4ms)
I, [2019-08-16T10:35:29.724830 #1470]  INFO -- :   Rendered plugins/redmine_people/app/views/common/_layout_bottom.html.erb (1.1ms)
I, [2019-08-16T10:35:29.725344 #1470]  INFO -- : Completed 200 OK in 189ms (Views: 171.9ms | ActiveRecord: 3.7ms)
I, [2019-08-16T10:35:44.148310 #1470]  INFO -- : Started POST "/entity_generator" for 192.168.133.1 at 2019-08-16 10:35:44 -0300
I, [2019-08-16T10:35:44.150153 #1470]  INFO -- : Processing by EntityGeneratorController#create as HTML
I, [2019-08-16T10:35:44.150270 #1470]  INFO -- :   Parameters: {"utf8"=>"âœ“", "authenticity_token"=>"Fa5ID78wjwFltM24U8HIgsjR6dUw+VZuUT7YkQUdSvPyxjpu8gbGU/wMJzjbTLyvapyJpJYvlwhZSP890kr+jg==", "plugin_create"=>"1", "plugin_name"=>"Prueb", "entities"=>{"0"=>{"entity_name"=>"Prueba", "entity_options"=>["--mail", "--acts-as-activity_provider", "--acts-as-attachable", "--acts-as-customizable", "--acts-as-event", "--acts-as-searchable"], "basic_fields"=>["name", "--author", "--project"]}}, "commit"=>"Crear"}
I, [2019-08-16T10:35:44.162837 #1470]  INFO -- :   Current user: user (id=1)
I, [2019-08-16T10:35:45.045066 #1470]  INFO -- : Completed 500 Internal Server Error in 895ms (ActiveRecord: 5.0ms)
F, [2019-08-16T10:35:45.047233 #1470] FATAL -- : 
NameError (uninitialized constant ActiveRecord::Migration::Current):
  plugins/redmine_entity_generator/app/controllers/entity_generator_controller.rb:23:in `block in create'
  plugins/redmine_entity_generator/app/controllers/entity_generator_controller.rb:20:in `each'
  plugins/redmine_entity_generator/app/controllers/entity_generator_controller.rb:20:in `each_with_index'
  plugins/redmine_entity_generator/app/controllers/entity_generator_controller.rb:20:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
