### ISSUE TITLE
error in the creation of an entity with custom fields

### ISSUE THREAD

**Issue by schildg** [easyredmine/redmine_entity_generator#11]
error in the creation of an entity with custom fields

I, [2019-06-27T14:55:02.915715 #31027]  INFO -- : Started POST "/catalogo_de_servicios" for 192.168.100.101 at 2019-06-27 14:55:02 -0300
I, [2019-06-27T14:55:02.919261 #31027]  INFO -- : Processing by CatalogoDeServiciosController#create as HTML
I, [2019-06-27T14:55:02.919440 #31027]  INFO -- :   Parameters: {"utf8"=>"âœ“", "authenticity_token"=>"CqwA/nj/AiHBmineFZpEW+SeNPFFdzmJ5SFod/HRCKq0XWtf79uoyWuzS4FmOt5ZNCyUkn4mmL42B3m9STqJaw==", "catalogo_de_servicio"=>{"project_id"=>"37", "name"=>"BBVA", "author_id"=>"84", "cliente_id"=>"1", "custom_field_values"=>{"66"=>["DigitalSignage", ""]}}, "commit"=>"Crear"}
I, [2019-06-27T14:55:03.059317 #31027]  INFO -- :   Current user: gschild (id=84)
I, [2019-06-27T14:55:03.638164 #31027]  INFO -- :   Rendered plugins/redmine_sidesys/app/views/catalogo_de_servicio_mailer/catalogo_de_servicio_added.text.erb within layouts/mailer (6.0ms)
I, [2019-06-27T14:55:03.664360 #31027]  INFO -- :   Rendered plugins/redmine_sidesys/app/views/catalogo_de_servicio_mailer/catalogo_de_servicio_added.html.erb within layouts/mailer (9.2ms)
I, [2019-06-27T14:55:03.994201 #31027]  INFO -- : Redirected to http://192.168.100.192/catalogo_de_servicios/1
I, [2019-06-27T14:55:03.994540 #31027]  INFO -- : Completed 302 Found in 1075ms (ActiveRecord: 415.1ms)
I, [2019-06-27T14:55:04.235940 #31027]  INFO -- : Started GET "/catalogo_de_servicios/1" for 192.168.100.101 at 2019-06-27 14:55:04 -0300
I, [2019-06-27T14:55:04.245941 #31027]  INFO -- : Processing by CatalogoDeServiciosController#show as HTML
I, [2019-06-27T14:55:04.246058 #31027]  INFO -- :   Parameters: {"id"=>"1"}
I, [2019-06-27T14:55:04.266677 #31027]  INFO -- :   Current user: gschild (id=84)
I, [2019-06-27T14:55:04.536156 #31027]  INFO -- :   Rendered vendor/bundle/ruby/2.3.0/gems/redmine_extensions-0.3.00/app/views/redmine_extensions/_custom_field_rows.html.erb (190.1ms)
I, [2019-06-27T14:55:04.541071 #31027]  INFO -- :   Rendered plugins/redmine_sidesys/app/views/catalogo_de_servicios/show.html.erb within layouts/base (219.9ms)
I, [2019-06-27T14:55:04.541823 #31027]  INFO -- : Completed 500 Internal Server Error in 296ms (ActiveRecord: 24.3ms)
F, [2019-06-27T14:55:04.548984 #31027] FATAL -- : 
ActionView::Template::Error (undefined method `translated_name' for #<CatalogoDeServicioCustomField:0x00007f09b9708658>
Did you mean?  transaction):
    3:   left_value = custom_field_values[row]
    4:   right_value = custom_field_values[row + half_size] %>
    5:   <tr>
    6:     <th><%= left_value ? h(left_value.custom_field.translated_name) : '' %></th>
    7:     <td><%= left_value ? show_value(left_value, true) : '' %></td>
    8:     <th><%= right_value ? h(right_value.custom_field.translated_name) : '' %></th>
    9:     <td><%= right_value ? show_value(right_value, true) : '' %></td>
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  plugins/redmine_sidesys/app/views/catalogo_de_servicios/show.html.erb:12:in `_74faaf10c831384e1fd62ae31620c6f5'
  plugins/redmine_sidesys/app/controllers/catalogo_de_servicios_controller.rb:26:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'

I, [2019-06-27T14:55:11.960214 #32608]  INFO -- : Starting Maintenance Mode plugin for Redmine
W, [2019-06-27T14:55:12.259662 #32608]  WARN -- : DEPRECATION WARNING: The acts_as_list plugin will be removed from Redmine 4 core, use the acts_as_list gem or similar implementation instead. (called from acts_as_list at /opt/bitnami/apps/redmine/htdocs/lib/plugins/acts_as_list/lib/active_record/acts/list.rb:34)

**Comment by ondra-m** [comment]
What version of Redmine do you have?

**Comment by schildg** [comment]
These are the data of the particular environment, where this error occurs and that of #10

Environment:
  Redmine version                3.4.8.stable.26
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Cvs                            1.12.13
  Git                            2.14.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.5.2
  advanced_roadmap               0.12.0
  computed_custom_field          1.0.7
  contracts                      2.4
  el_capitan                     1.0.0
  extra_queries                  2.3.6
  gantt_extension                0.2
  global_roles                   2.2.3
  redmine_agile                  1.4.7
  redmine_base_deface            0.0.1
  redmine_checklists             3.1.14
  redmine_ckeditor               1.1.7
  redmine_custom_reports         0.1.5
  redmine_custom_workflows       0.1.6
  redmine_customize_core_fields  1.0.0
  redmine_dmsf                   1.6.2
  redmine_edit_custom_fields     0.0.5
  redmine_entity_generator       2016
  redmine_helpdesk               0.0.15
  redmine_highlightjs            1.0.3
  redmine_issue_badge            0.0.6
  redmine_issue_templates        0.2.1
  redmine_ldap_sync              2.1.1.devel
  redmine_lightbox2              0.4.4
  redmine_maintenance_mode       2.1.0
  redmine_monitoring_controlling 0.1.1
  redmine_my_page                0.1.13
  redmine_people                 1.4.0
  redmine_sidesys                2019
  redmine_tags                   3.2.2
  redmine_workflow_enhancements  0.5.0
  redmine_xapian                 1.6.8
  sidebar_hide                   0.0.8


Gems included by the bundle:
  * actionmailer (4.2.8)
  * actionpack (4.2.8)
  * actionpack-xml_parser (1.0.2)
  * actionview (4.2.8)
  * activejob (4.2.8)
  * activemodel (4.2.8)
  * activerecord (4.2.8)
  * activerecord-session_store (1.1.0)
  * activerecord-tableless (1.0.2)
  * activesupport (4.2.8)
  * acts-as-taggable-on (4.0.0)
  * addressable (2.5.2)
  * arel (6.0.4)
  * builder (3.2.3)
  * bundler (1.14.6)
  * business_time (0.9.3)
  * climate_control (0.2.0)
  * coderay (1.1.2)
  * concurrent-ruby (1.0.5)
  * crass (1.0.2)
  * css_parser (1.6.0)
  * dalli (2.7.6)
  * deface (1.2.0)
  * erubis (2.7.0)
  * globalid (0.4.1)
  * htmlentities (4.3.4)
  * i18n (0.7.0)
  * jquery-rails (3.1.4)
  * kaminari (1.1.1)
  * kaminari-actionview (1.1.1)
  * kaminari-activerecord (1.1.1)
  * kaminari-core (1.1.1)
  * liquid (2.6.3)
  * loofah (2.1.1)
  * mail (2.6.6)
  * mime-types (3.1)
  * mime-types-data (3.2016.0521)
  * mimemagic (0.3.2)
  * mini_portile2 (2.1.0)
  * minitest (5.10.3)
  * multi_json (1.12.2)
  * mysql2 (0.4.9)
  * net-ldap (0.12.1)
  * nokogiri (1.7.2)
  * ox (2.9.0)
  * pandoc-ruby (2.0.2)
  * paperclip (6.1.0)
  * polyglot (0.3.5)
  * protected_attributes (1.1.4)
  * public_suffix (3.0.0)
  * rack (1.6.8)
  * rack-openid (1.4.2)
  * rack-raw-upload (1.1.1)
  * rack-test (0.6.3)
  * rails (4.2.8)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.8)
  * rails-html-sanitizer (1.0.3)
  * railties (4.2.8)
  * rainbow (2.2.2)
  * rake (12.2.1)
  * rbpdf (1.19.3)
  * rbpdf-font (1.19.1)
  * redcarpet (3.4.0)
  * redmine_crm (0.0.42)
  * redmine_extensions (0.3.00)
  * request_store (1.0.5)
  * rich (1.4.8 15f6353)
  * rmagick (2.16.0)
  * roadie (3.2.2)
  * roadie-rails (1.1.1)
  * ruby-openid (2.3.0)
  * rubyzip (1.2.1)
  * simple_enum (2.3.0)
  * sprockets (3.7.1)
  * sprockets-rails (3.2.1)
  * terrapin (0.6.0)
  * thor (0.20.0)
  * thread_safe (0.3.6)
  * tzinfo (1.2.3)
  * useragent (0.16.8)
  * uuidtools (2.1.5)
  * vcard (0.2.15)
  * will_paginate (3.0.12)
  * zip-zip (0.3)

**Comment by jiribruk** [comment]
Thank you for your information. we will try to emulate it, and if it is a generator error, fix it.

**Comment by jiribruk** [comment]
Fixed in redmine_extension version '0.3.2'
