### ISSUE TITLE
problem after updating the gem redmine_extensions 0.3.3

### ISSUE THREAD

**Issue by schildg** [easyredmine/redmine_entity_generator#12]
Hello, I have the following problem after updating the gem redmine_extensions 0.3.3, when I am generating the entities I throw the following error, why is that?

I, [2019-08-16T10:35:29.193841 #1470]  INFO -- : Started GET "/entity_generator/new" for 192.168.133.1 at 2019-08-16 10:35:29 -0300
I, [2019-08-16T10:35:29.536318 #1470]  INFO -- : Processing by EntityGeneratorController#new as HTML
I, [2019-08-16T10:35:29.546289 #1470]  INFO -- :   Current user: user (id=1)
I, [2019-08-16T10:35:29.654423 #1470]  INFO -- :   Rendered plugins/redmine_entity_generator/app/views/entity_generator/_new_entity.html.erb (9.3ms)
I, [2019-08-16T10:35:29.654599 #1470]  INFO -- :   Rendered plugins/redmine_entity_generator/app/views/entity_generator/_form.html.erb (24.1ms)
I, [2019-08-16T10:35:29.655888 #1470]  INFO -- :   Rendered plugins/redmine_entity_generator/app/views/entity_generator/new.html.erb within layouts/base (54.7ms)
I, [2019-08-16T10:35:29.669594 #1470]  INFO -- :   Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (4.8ms)
I, [2019-08-16T10:35:29.670973 #1470]  INFO -- :   Rendered plugins/advanced_roadmap/app/views/hooks/_stylesheet.html.erb (0.5ms)
I, [2019-08-16T10:35:29.672098 #1470]  INFO -- :   Rendered plugins/extra_queries/app/views/extra_queries/hooks/_html_head.html.erb (0.3ms)
I, [2019-08-16T10:35:29.674004 #1470]  INFO -- :   Rendered plugins/global_roles/app/views/hooks/global_roles/_head.html.erb (0.3ms)
I, [2019-08-16T10:35:29.676107 #1470]  INFO -- :   Rendered plugins/redmine_contacts/app/views/contacts_issues/_additional_assets.html.erb (1.0ms)
I, [2019-08-16T10:35:29.677004 #1470]  INFO -- : redmine_highlightjs2: supported browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
I, [2019-08-16T10:35:29.686025 #1470]  INFO -- :   Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.1ms)
I, [2019-08-16T10:35:29.712519 #1470]  INFO -- :   Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.2ms)
I, [2019-08-16T10:35:29.713708 #1470]  INFO -- :   Rendered plugins/global_roles/app/views/hooks/global_roles/_view_layouts_base_body_bottom.html.erb (0.3ms)
I, [2019-08-16T10:35:29.714801 #1470]  INFO -- :   Rendered plugins/redmine_contacts/app/views/common/_contacts_select2_data.html.erb (0.4ms)
I, [2019-08-16T10:35:29.723339 #1470]  INFO -- :   Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (7.5ms)
I, [2019-08-16T10:35:29.724719 #1470]  INFO -- :   Rendered plugins/redmine_people/app/views/common/_people_select2_data.html.erb (0.4ms)
I, [2019-08-16T10:35:29.724830 #1470]  INFO -- :   Rendered plugins/redmine_people/app/views/common/_layout_bottom.html.erb (1.1ms)
I, [2019-08-16T10:35:29.725344 #1470]  INFO -- : Completed 200 OK in 189ms (Views: 171.9ms | ActiveRecord: 3.7ms)
I, [2019-08-16T10:35:44.148310 #1470]  INFO -- : Started POST "/entity_generator" for 192.168.133.1 at 2019-08-16 10:35:44 -0300
I, [2019-08-16T10:35:44.150153 #1470]  INFO -- : Processing by EntityGeneratorController#create as HTML
I, [2019-08-16T10:35:44.150270 #1470]  INFO -- :   Parameters: {"utf8"=>"âœ“", "authenticity_token"=>"Fa5ID78wjwFltM24U8HIgsjR6dUw+VZuUT7YkQUdSvPyxjpu8gbGU/wMJzjbTLyvapyJpJYvlwhZSP890kr+jg==", "plugin_create"=>"1", "plugin_name"=>"Prueb", "entities"=>{"0"=>{"entity_name"=>"Prueba", "entity_options"=>["--mail", "--acts-as-activity_provider", "--acts-as-attachable", "--acts-as-customizable", "--acts-as-event", "--acts-as-searchable"], "basic_fields"=>["name", "--author", "--project"]}}, "commit"=>"Crear"}
I, [2019-08-16T10:35:44.162837 #1470]  INFO -- :   Current user: user (id=1)
I, [2019-08-16T10:35:45.045066 #1470]  INFO -- : Completed 500 Internal Server Error in 895ms (ActiveRecord: 5.0ms)
F, [2019-08-16T10:35:45.047233 #1470] FATAL -- : 
NameError (uninitialized constant ActiveRecord::Migration::Current):
  plugins/redmine_entity_generator/app/controllers/entity_generator_controller.rb:23:in `block in create'
  plugins/redmine_entity_generator/app/controllers/entity_generator_controller.rb:20:in `each'
  plugins/redmine_entity_generator/app/controllers/entity_generator_controller.rb:20:in `each_with_index'
  plugins/redmine_entity_generator/app/controllers/entity_generator_controller.rb:20:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

_Originally posted by @schildg in https://github.com/easyredmine/redmine_entity_generator/issues/10#issuecomment-522013980_

**Comment by jiribruk** [comment]
You need Redmine with Rails version > 5. Becouse this ActiveRecord::Migration::Current is from Rails 5.
