### ISSUE TITLE
translation missing: en.note_generator_head

### ISSUE THREAD

**Issue by Atmis** [easyredmine/redmine_entity_generator#14]
Hello,

The string "note_generator_head" is missing in the locales files en.yml and ja.yml, only present in cs.yml

"note_generator_head: We recommend using only users with programmer's knowledge"

![image](https://user-images.githubusercontent.com/5329747/80083372-d4600b80-8555-11ea-8ffb-5dda016972bb.png)

Pierre

**Comment by luk4s** [comment]
Hello @Atmis ,
thank you for apointing out the missing langfile key.
