### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by FreddySpaghetty** [easyredmine/redmine_entity_generator#18]
here it is my environment information 

Environment:
  Redmine version                4.1.3.stable
  Ruby version                   2.6.8-p205 (2021-07-07) [x86_64-linux]
  Rails version                  5.2.5
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  nuovo_plugiin                  2022
  redmine_attachment_categories  2.0.0
  redmine_checklists             3.1.19
  redmine_contacts               4.3.4
  redmine_custom_auto_complete   0.0.1
  redmine_entity_generator       2016
  redmine_lightbox2              0.5.1
  redmine_smile_project_enumerations_custom_field_format 1.3.15
  
  This is my Gemfile.lock
  GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.5)
      actionpack (= 5.2.5)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.5)
      actionpack (= 5.2.5)
      actionview (= 5.2.5)
      activejob (= 5.2.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.5)
      actionview (= 5.2.5)
      activesupport (= 5.2.5)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionpack-xml_parser (2.0.1)
      actionpack (>= 5.0)
      railties (>= 5.0)
    actionview (5.2.5)
      activesupport (= 5.2.5)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.2.5)
      activesupport (= 5.2.5)
      globalid (>= 0.3.6)
    activemodel (5.2.5)
      activesupport (= 5.2.5)
    activerecord (5.2.5)
      activemodel (= 5.2.5)
      activesupport (= 5.2.5)
      arel (>= 9.0)
    activestorage (5.2.5)
      actionpack (= 5.2.5)
      activerecord (= 5.2.5)
      marcel (~> 1.0.0)
    activesupport (5.2.5)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    arel (9.0.0)
    ast (2.4.2)
    builder (3.2.4)
    capybara (3.25.0)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (~> 1.5)
      xpath (~> 3.2)
    childprocess (3.0.0)
    concurrent-ruby (1.1.9)
    crass (1.0.6)
    css_parser (1.9.0)
      addressable
    csv (3.1.9)
    docile (1.4.0)
    erubi (1.10.0)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    htmlentities (4.3.4)
    i18n (1.6.0)
      concurrent-ruby (~> 1.0)
    jaro_winkler (1.5.4)
    json (2.5.1)
    liquid (2.6.3)
    loofah (2.10.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.1)
    method_source (1.0.0)
    mini_magick (4.9.5)
    mini_mime (1.0.3)
    mini_portile2 (2.5.3)
    minitest (5.14.4)
    mocha (1.13.0)
    mysql2 (0.5.3)
    net-ldap (0.16.3)
    nio4r (2.5.7)
    nokogiri (1.11.7)
      mini_portile2 (~> 2.5.0)
      racc (~> 1.4)
    parallel (1.20.1)
    parser (3.0.2.0)
      ast (~> 2.4.1)
    public_suffix (4.0.6)
    puma (3.12.6)
    racc (1.5.2)
    rack (2.2.3)
    rack-openid (1.4.2)
      rack (>= 1.1.0)
      ruby-openid (>= 2.1.8)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.5)
      actioncable (= 5.2.5)
      actionmailer (= 5.2.5)
      actionpack (= 5.2.5)
      actionview (= 5.2.5)
      activejob (= 5.2.5)
      activemodel (= 5.2.5)
      activerecord (= 5.2.5)
      activestorage (= 5.2.5)
      activesupport (= 5.2.5)
      bundler (>= 1.3.0)
      railties (= 5.2.5)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (5.2.5)
      actionpack (= 5.2.5)
      activesupport (= 5.2.5)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rainbow (3.0.0)
    rake (13.0.6)
    rbpdf (1.20.1)
      htmlentities
      rbpdf-font (~> 1.19.0)
    rbpdf-font (1.19.1)
    redcarpet (3.5.1)
    redmine_crm (0.0.56)
      liquid (< 2.6.4)
      rails
      rubyzip
    redmine_extensions (0.4.3)
      rails (>= 4.2, < 6.2)
    regexp_parser (1.8.2)
    request_store (1.4.1)
      rack (>= 1.4)
    roadie (4.0.0)
      css_parser (~> 1.4)
      nokogiri (~> 1.8)
    roadie-rails (2.1.1)
      railties (>= 5.1, < 6.1)
      roadie (>= 3.1, < 5.0)
    rouge (3.12.0)
    rubocop (0.76.0)
      jaro_winkler (~> 1.5.1)
      parallel (~> 1.10)
      parser (>= 2.6)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 1.7)
    rubocop-performance (1.5.2)
      rubocop (>= 0.71.0)
    rubocop-rails (2.3.2)
      rack (>= 1.1)
      rubocop (>= 0.72.0)
    ruby-ole (1.2.12.2)
    ruby-openid (2.9.2)
    ruby-progressbar (1.11.0)
    rubyzip (2.3.2)
    selenium-webdriver (3.142.7)
      childprocess (>= 0.5, < 4.0)
      rubyzip (>= 1.2.2)
    simplecov (0.17.1)
      docile (~> 1.1)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)
    spreadsheet (1.3.0)
      ruby-ole
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.2)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (1.1.0)
    thread_safe (0.3.6)
    tzinfo (1.2.9)
      thread_safe (~> 0.1)
    unicode-display_width (1.6.1)
    vcard (0.3.0)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    yard (0.9.26)

PLATFORMS
  ruby

DEPENDENCIES
  actionpack-xml_parser
  bundler (>= 1.5.0)
  capybara (~> 3.25.0)
  csv (~> 3.1.1)
  ffi
  i18n (~> 1.6.0)
  mail (~> 2.7.1)
  marcel
  mini_magick (~> 4.9.5)
  mini_mime (~> 1.0.1)
  mocha (>= 1.4.0)
  mysql2 (~> 0.5.0)
  net-ldap (~> 0.16.0)
  nokogiri (~> 1.11.1)
  puma (~> 3.7)
  rack-openid
  rails (= 5.2.5)
  rails-dom-testing
  rbpdf (~> 1.20.0)
  redcarpet (~> 3.5.1)
  redmine_crm
  redmine_extensions
  request_store (~> 1.4.1)
  roadie-rails (~> 2.1.0)
  rouge (~> 3.12.0)
  rubocop (~> 0.76.0)
  rubocop-performance (~> 1.5.0)
  rubocop-rails (~> 2.3.0)
  ruby-openid (~> 2.9.2)
  selenium-webdriver
  simplecov (~> 0.17.0)
  spreadsheet
  tzinfo-data
  vcard
  yard

RUBY VERSION
   ruby 2.6.8p205

BUNDLED WITH
   1.17.2
   
   
   
   i'm running thi with docker so when i create the entity i just restart the container cause in the docker-compose i have the migrate
   
   i Tryied to switch a lot of redmine version but nothing works
   
   i have this error when i access to the ./new_entity_created ("issues") page
   
![image](https://user-images.githubusercontent.com/101812367/169895602-c36805ef-cf57-4971-8826-38105649e71c.png)

   i also had a similar error when (with other redmine versions) i reached to render the entity page and when i was creating a new entity
   
   
![image](https://user-images.githubusercontent.com/101812367/169895763-4d9f12bd-a2d0-41de-a904-2b24d7250efe.png)
with this environment
![image](https://user-images.githubusercontent.com/101812367/169895924-3127bb42-b71d-4417-ad01-1aa39c353a26.png)

Any possible tips for fix this?

**Comment by luk4s** [comment]
Hi @FreddySpaghetty , this plugin is currently unmaintained. Its original provide just "skeleton" of new entity, which needs to be finish/adjust to working state. Also primary focused on Easy Redmine...

I see from your log that server just return 500, if you provide more detail = fulltrace of this error, I can help you more. Probably generator prepare model with some methods, which are no longer exists in current version of Easy Redmine or Redmine, or is in conflict with some of your plugins.

Log should be located in `log/production.log` file, in place where you have redmine installed.

**Comment by FreddySpaghetty** [comment]
thanks lukas
I already removed all other pluging in order to avoid conflicts

this is my full log 
login -> Entity in the top tab -> Create a new entity

192.168.126.1 - - [28/May/2022:15:27:16 UTC] "GET /login HTTP/1.1" 200 6119
http://192.168.126.129:3210/ -> /login
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "POST /login HTTP/1.1" 302 94
http://192.168.126.129:3210/login -> /login
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET / HTTP/1.1" 200 6284
http://192.168.126.129:3210/login -> /
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET /javascripts/redmine_extensions/blocking_render.js?1653751553 HTTP/1.1" 304 0
http://192.168.126.129:3210/ -> /javascripts/redmine_extensions/blocking_render.js?1653751553
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET /javascripts/redmine_extensions/blocking_utils.js?1653751553 HTTP/1.1" 304 0
http://192.168.126.129:3210/ -> /javascripts/redmine_extensions/blocking_utils.js?1653751553
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET /javascripts/redmine_extensions/blocking_schedule.js?1653751553 HTTP/1.1" 304 0
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET /javascripts/redmine_extensions/blocking_polyfill.js?1653751553 HTTP/1.1" 304 0
http://192.168.126.129:3210/ -> /javascripts/redmine_extensions/blocking_polyfill.js?1653751553
http://192.168.126.129:3210/ -> /javascripts/redmine_extensions/blocking_schedule.js?1653751553
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET /javascripts/redmine_extensions/blocking_namespace.js?1653751553 HTTP/1.1" 304 0
http://192.168.126.129:3210/ -> /javascripts/redmine_extensions/blocking_namespace.js?1653751553
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET /javascripts/redmine_extensions/blocking_module.js?1653751553 HTTP/1.1" 304 0
http://192.168.126.129:3210/ -> /javascripts/redmine_extensions/blocking_module.js?1653751553
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET /javascripts/redmine_extensions/blocking_dynamic_loading.js?1653751553 HTTP/1.1" 304 0
http://192.168.126.129:3210/ -> /javascripts/redmine_extensions/blocking_dynamic_loading.js?1653751553
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET /javascripts/redmine_extensions/redmine_extensions.js?1653751553 HTTP/1.1" 304 0
http://192.168.126.129:3210/ -> /javascripts/redmine_extensions/redmine_extensions.js?1653751553
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET /javascripts/redmine_extensions/render_polyfill.js?1653751553 HTTP/1.1" 304 0
http://192.168.126.129:3210/ -> /javascripts/redmine_extensions/render_polyfill.js?1653751553
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET /javascripts/redmine_extensions/easy_togglers.js?1653751553 HTTP/1.1" 304 0
http://192.168.126.129:3210/ -> /javascripts/redmine_extensions/easy_togglers.js?1653751553
192.168.126.1 - - [28/May/2022:15:27:21 UTC] "GET /javascripts/redmine_extensions/jquery.entityarray.js?1653751553 HTTP/1.1" 304 0
http://192.168.126.129:3210/ -> /javascripts/redmine_extensions/jquery.entityarray.js?1653751553
192.168.126.1 - - [28/May/2022:15:27:26 UTC] "GET /dummy_ent_names HTTP/1.1" 200 13160
http://192.168.126.129:3210/ -> /dummy_ent_names
I, [2022-05-28T15:26:14.726759 #1]  INFO -- :   Rendered plugins/dummy_plug_name/app/views/dummy_ent_names/_sidebar.html.erb (1.7ms)
I, [2022-05-28T15:26:14.726901 #1]  INFO -- :   Rendered plugins/dummy_plug_name/app/views/dummy_ent_names/new.html.erb within layouts/base (13.2ms)
I, [2022-05-28T15:26:14.727207 #1]  INFO -- : Completed 500 Internal Server Error in 44ms (ActiveRecord: 12.2ms)
F, [2022-05-28T15:26:14.729479 #1] FATAL -- :
F, [2022-05-28T15:26:14.729609 #1] FATAL -- : SyntaxError (/usr/src/redmine/plugins/dummy_plug_name/app/views/dummy_ent_names/_sidebar.html.erb:7: syntax error, unexpected '<', expecting ')'
  <% end );@output_buffer.safe_a...
  ^
/usr/src/redmine/plugins/dummy_plug_name/app/views/dummy_ent_names/_sidebar.html.erb:12: syntax error, unexpected ensure, expecting end
          ensure
          ^~~~~~
/usr/src/redmine/plugins/dummy_plug_name/app/views/dummy_ent_names/_sidebar.html.erb:14: syntax error, unexpected end-of-input, expecting end):
F, [2022-05-28T15:26:14.729658 #1] FATAL -- :
F, [2022-05-28T15:26:14.729689 #1] FATAL -- : plugins/dummy_plug_name/app/views/dummy_ent_names/_sidebar.html.erb:7: syntax error, unexpected '<', expecting ')'
plugins/dummy_plug_name/app/views/dummy_ent_names/_sidebar.html.erb:12: syntax error, unexpected ensure, expecting end
plugins/dummy_plug_name/app/views/dummy_ent_names/_sidebar.html.erb:14: syntax error, unexpected end-of-input, expecting end
plugins/dummy_plug_name/app/views/dummy_ent_names/new.html.erb:7:in `block in _plugins_dummy_plug_name_app_views_dummy_ent_names_new_html_erb___1974175976863816668_70185042011420'
plugins/dummy_plug_name/app/views/dummy_ent_names/new.html.erb:6:in `_plugins_dummy_plug_name_app_views_dummy_ent_names_new_html_erb___1974175976863816668_70185042011420'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
I, [2022-05-28T15:27:14.330054 #1]  INFO -- : Started POST "/logout" for 192.168.126.1 at 2022-05-28 15:27:14 +0000
I, [2022-05-28T15:27:14.333304 #1]  INFO -- : Processing by AccountController#logout as HTML
I, [2022-05-28T15:27:14.333434 #1]  INFO -- :   Parameters: {"authenticity_token"=>"p9EbdZH877tjd73TpQforPTKYkUCavzli5CHjy9lroYWnfC57LAoLOuptJFglkay82OIqvww2Dcscy0D2OfoEg"}
I, [2022-05-28T15:27:14.345195 #1]  INFO -- :   Current user: admin (id=1)
I, [2022-05-28T15:27:14.358495 #1]  INFO -- : Redirected to http://192.168.126.129:3210/
I, [2022-05-28T15:27:14.358741 #1]  INFO -- : Completed 302 Found in 25ms (ActiveRecord: 14.9ms)
I, [2022-05-28T15:27:14.377496 #1]  INFO -- : Started GET "/" for 192.168.126.1 at 2022-05-28 15:27:14 +0000
I, [2022-05-28T15:27:14.378589 #1]  INFO -- : Processing by WelcomeController#index as HTML
I, [2022-05-28T15:27:14.389085 #1]  INFO -- :   Current user: anonymous
I, [2022-05-28T15:27:14.610051 #1]  INFO -- :   Rendering welcome/index.html.erb within layouts/base
I, [2022-05-28T15:27:14.619936 #1]  INFO -- :   Rendered welcome/index.html.erb within layouts/base (9.8ms)
I, [2022-05-28T15:27:14.678054 #1]  INFO -- : Completed 200 OK in 299ms (Views: 53.2ms | ActiveRecord: 60.1ms)
I, [2022-05-28T15:27:16.266488 #1]  INFO -- : Started GET "/login" for 192.168.126.1 at 2022-05-28 15:27:16 +0000
I, [2022-05-28T15:27:16.268599 #1]  INFO -- : Processing by AccountController#login as HTML
I, [2022-05-28T15:27:16.283441 #1]  INFO -- :   Current user: anonymous
I, [2022-05-28T15:27:16.286442 #1]  INFO -- :   Rendering account/login.html.erb within layouts/base
I, [2022-05-28T15:27:16.305744 #1]  INFO -- :   Rendered account/login.html.erb within layouts/base (19.2ms)
I, [2022-05-28T15:27:16.337306 #1]  INFO -- : Completed 200 OK in 68ms (Views: 30.1ms | ActiveRecord: 29.9ms)
I, [2022-05-28T15:27:21.744228 #1]  INFO -- : Started POST "/login" for 192.168.126.1 at 2022-05-28 15:27:21 +0000
I, [2022-05-28T15:27:21.745660 #1]  INFO -- : Processing by AccountController#login as HTML
I, [2022-05-28T15:27:21.745777 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"XdTNMaYC170AA9TpK4PYhbRveP5pgoNILzA3pKlunYCIP8a9NBc9DFZe4oktxoC_JaKqIhdsQwlAGhgOFlzhCw", "back_url"=>"/", "username"=>"admin", "password"=>"[FILTERED]", "login"=>"Entra"}
I, [2022-05-28T15:27:21.754104 #1]  INFO -- :   Current user: anonymous
I, [2022-05-28T15:27:21.762455 #1]  INFO -- : Successful authentication for 'admin' from 192.168.126.1 at 2022-05-28 15:27:21 UTC
I, [2022-05-28T15:27:21.813444 #1]  INFO -- : Redirected to http://192.168.126.129:3210/
I, [2022-05-28T15:27:21.813788 #1]  INFO -- : Completed 302 Found in 68ms (ActiveRecord: 34.9ms)
I, [2022-05-28T15:27:21.827230 #1]  INFO -- : Started GET "/" for 192.168.126.1 at 2022-05-28 15:27:21 +0000
I, [2022-05-28T15:27:21.828370 #1]  INFO -- : Processing by WelcomeController#index as HTML
I, [2022-05-28T15:27:21.841322 #1]  INFO -- :   Current user: admin (id=1)
I, [2022-05-28T15:27:21.847285 #1]  INFO -- :   Rendering welcome/index.html.erb within layouts/base
I, [2022-05-28T15:27:21.853157 #1]  INFO -- :   Rendered welcome/index.html.erb within layouts/base (5.7ms)
I, [2022-05-28T15:27:21.878193 #1]  INFO -- : Completed 200 OK in 49ms (Views: 24.8ms | ActiveRecord: 15.0ms)
I, [2022-05-28T15:27:26.915367 #1]  INFO -- : Started GET "/dummy_ent_names" for 192.168.126.1 at 2022-05-28 15:27:26 +0000
I, [2022-05-28T15:27:26.919265 #1]  INFO -- : Processing by DummyEntNamesController#index as HTML
I, [2022-05-28T15:27:26.933339 #1]  INFO -- :   Current user: admin (id=1)
I, [2022-05-28T15:27:26.945219 #1]  INFO -- :   Rendering plugins/dummy_plug_name/app/views/dummy_ent_names/index.html.erb within layouts/base
I, [2022-05-28T15:27:26.952311 #1]  INFO -- :   Rendered queries/_filters.html.erb (5.3ms)
I, [2022-05-28T15:27:26.954177 #1]  INFO -- :   Rendered queries/_columns.html.erb (1.5ms)
I, [2022-05-28T15:27:26.954693 #1]  INFO -- :   Rendered queries/_query_form.html.erb (8.8ms)
I, [2022-05-28T15:27:26.955123 #1]  INFO -- :   Rendered plugins/dummy_plug_name/app/views/dummy_ent_names/index.html.erb within layouts/base (9.8ms)
I, [2022-05-28T15:27:26.986157 #1]  INFO -- : Completed 200 OK in 67ms (Views: 28.6ms | ActiveRecord: 21.1ms)
I, [2022-05-28T15:27:28.805829 #1]  INFO -- : Started GET "/dummy_ent_names/new" for 192.168.126.1 at 2022-05-28 15:27:28 +0000
I, [2022-05-28T15:27:28.807499 #1]  INFO -- : Processing by DummyEntNamesController#new as HTML
I, [2022-05-28T15:27:28.821185 #1]  INFO -- :   Current user: admin (id=1)
I, [2022-05-28T15:27:28.822044 #1]  INFO -- :   Rendering plugins/dummy_plug_name/app/views/dummy_ent_names/new.html.erb within layouts/base
I, [2022-05-28T15:27:28.823839 #1]  INFO -- :   Rendered plugins/dummy_plug_name/app/views/dummy_ent_names/_form.html.erb (1.6ms)
192.168.126.1 - - [28/May/2022:15:27:28 UTC] "GET /dummy_ent_names/new HTTP/1.1" 500 648
http://192.168.126.129:3210/dummy_ent_names -> /dummy_ent_names/new

**Comment by luk4s** [comment]
Hello @FreddySpaghetty  ,
We just release new version of `redmine_extensions` which contains fixed generator of entity (https://rubygems.org/gems/redmine_extensions/versions/0.4.4)

So please update redmine_extensions in your redmine, remove previous generated plugin and then generate plugin again. 
OR fix your `_sidebar.html.erb` 

In your case open `plugins/dummy_plug_name/app/views/dummy_ent_names/_sidebar.html.erb`, go to line ~6 and add to end of this line: ` %>`
