### ISSUE TITLE
Not workin at bitnami 3.3.3

### ISSUE THREAD

**Issue by smahou98** [easyredmine/redmine_entity_generator#3]
Hello,
I try to create a new entity on a:
Redmine version                3.3.3.stable
  Ruby version                   2.1.10-p492 (2016-04-01) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2

and have an 500 internal error.
Log shows like this:
NoMethodError (undefined method 'to_boolean' for "1":String
plugins/redmine_entity_generator/app/controllers/entity_generator_controller.rb:56:in 'find_plugin_name'

Can help me please?

**Comment by joshualamorie** [comment]
I have the same issue with a bitnami deployment of redmine 3.3.3-1

**Comment by joshualamorie** [comment]
I also had it occur with bitnami deployment of redmine 3.3.1-0

**Comment by ondra-m** [comment]
Try run `bundle update`

**Comment by joshualamorie** [comment]
Yeah, that appears to have improved things quite a bit.  I'm not able to add associations however.  It doesn't populate anything in the list of 'Association entity'.  Is this something that requires other components from Easy Redmine?
