### ISSUE TITLE
NameError (uninitialized constant EasyQuery)

### ISSUE THREAD

**Issue by Mutniks** [easyredmine/redmine_entity_generator#5]
On my redmine installation, I get a blank page once trying to access a newly generated entity. Production log shows NameError (uninitialized constant EasyQuery).

**Comment by luk4s** [comment]
Hi @Mutniks ,
I am sorry for delay. This is definetely bug in our generator. Currently you can replace `EasyQuery` with `Query`, its a workaround. 
Anyway thanks for report. We fixed it in generator and let you know.
