### ISSUE TITLE
undefined method `human_attribute_name' error

### ISSUE THREAD

**Issue by arturhefczyc** [easyredmine/redmine_entity_generator#8]
Everything seems to be working correctly. Plugin installed, and generating new plugin and entity works without any problems, migrated new plugin and restarted web server.

New plugin shows on the list.

However, when I try to open link for the new entity I get the error:

`NoMethodError (undefined method `human_attribute_name' for NewPlugin:Module):
  plugins/new_plugin/app/models/new_plugin_query.rb:6:in `initialize_available_filters'
  app/models/query.rb:597:in `available_filters'
  app/models/query.rb:374:in `build_from_params'
  app/helpers/queries_helper.rb:299:in `retrieve_query'
  plugins/new_plugin/app/controllers/new_plugin_controller.rb:21:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

Any suggestions would be very much appreciated.

I am using the generator plugin from today's master zip.
  Redmine version                3.4.5.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux]
  Rails version                  4.2.8

**Comment by NormanEdance** [comment]
Same here...
Redmine 4.0.x;
Ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]
Rails 5.2.3

**Comment by NormanEdance** [comment]
Seems like, It happens when plugin name and entity name are the same...

**Comment by jiribruk** [comment]
Problem is realy in same plugin name and entity name. It is not possible. Because system generate two same constant.
