### ISSUE TITLE
Error in Entity Generator

### ISSUE THREAD

**Issue by kithril** [easyredmine/redmine_entity_generator#9]
The following is cut and pasted from my internal_error.html file generated by EasyRedmine. It appears to me that it is missing the plugin name when calling dir_s_mkdir.

----

ActionView::Template::Error in EntityGenerator#create

Showing where line # raised:

Permission denied @ dir_s_mkdir - /plugins

Extracted source (around line #19):

17
18
19
20
21
22
              

	

    if @plugin_name.present? && @entities.present?
      associations = association_table(@entities)
      Rails::Generators.invoke('redmine_extensions:plugin', [@plugin_name]) if params[:plugin_create].to_boolean
      @entities.each_with_index do |entity, index|
        generator_arguments = prepare_generator_arguments_from_entity(entity, associations)

Rails.root: /home/bruce/vanillaeasy
Application Trace | Framework Trace | Full Trace | Redmine environment | SCM | Redmine Plugins | Request details

plugins/redmine_entity_generator/app/controllers/entity_generator_controller.rb:19:in `create'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/easysoftware/gems/rys/app/middleware/rys/feature_preload.rb:20:in `call'

Request

Parameters:

{"utf8"=>"\u2713",
 "authenticity_token"=>"6AXiobHz3XjKeM/hq2nHgLftnhv4yxSNKVFZ1bn5v5KLdpPSWTRr9C0kG5s0TMUvgegyT2ecyIbAdMrEgcuw0g==",
 "plugin_create"=>"1",
 "plugin_name"=>"EasyAcnz",
 "entities"=>{"0"=>{"entity_name"=>"EasyAcnzEntity",
 "basic_fields"=>["name"]}},
 "commit"=>"Save"}

Toggle session dump

_csrf_token: "Y3Nxc+jHtoznXNR6nyUCrzYFrFSfV9wL6SWTETgyD0A="
session_id: "66abaedab3c3c3dc44a5756856f03448"
sudo_timestamp: 1557103896
tk: "90329b9becdc4842e66daa0106957920015e01ae"
user_id: 1

Toggle env dump

GATEWAY_INTERFACE: "CGI/1.1"
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.5"
REMOTE_ADDR: "127.0.0.1"
REMOTE_HOST: "127.0.0.1"
SERVER_NAME: "localhost"
SERVER_PROTOCOL: "HTTP/1.1"

Response

Headers:

{"X-Frame-Options"=>"SAMEORIGIN",
 "X-XSS-Protection"=>"1; mode=block",
 "X-Content-Type-Options"=>"nosniff"}

**Comment by jiribruk** [comment]
Which versions ruby, rails, and redmine_extensions are used?

I tried reproduce it on: ruby 2.5.3p105 
                                 Rails 5.2.3
                                 redmine_extensions 0.3.3
And i can not reproduce your problem.
